POST http://localhost:8080/api/like-res/createLikeRes
Content-Type: application/json

{
    "user_id" : 1,
    "res_id" : 2
}

###

POST http://localhost:8080/api/like-res/unLikeRes
Content-Type: application/json

{
    "user_id" : 1,
    "res_id" : 2
}

###

GET http://localhost:8080/api/like-res/getLikeResByRestaurant/3
###

GET http://localhost:8080/api/like-res?res_id=3
###

GET http://localhost:8080/api/like-res/getLikeResByUser/1
###

GET http://localhost:8080/api/like-res?user_id=1
###

GET http://localhost:8080/api/like-res?res_id=1&user_id=3
###
